# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_Registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window_Registro(object):
    def setupUi(self, Window_Registro):
        Window_Registro.setObjectName("Window_Registro")
        Window_Registro.resize(866, 593)
        self.centralwidget = QtWidgets.QWidget(Window_Registro)
        self.centralwidget.setObjectName("centralwidget")
        self.Laber_Imagen = QtWidgets.QLabel(self.centralwidget)
        self.Laber_Imagen.setGeometry(QtCore.QRect(-10, -10, 831, 501))
        self.Laber_Imagen.setAutoFillBackground(False)
        self.Laber_Imagen.setText("")
        self.Laber_Imagen.setPixmap(QtGui.QPixmap("img\Fondo.png"))
        self.Laber_Imagen.setScaledContents(True)
        self.Laber_Imagen.setObjectName("Laber_Imagen")
        self.Label_Fonodo_Monocromatico = QtWidgets.QLabel(self.centralwidget)
        self.Label_Fonodo_Monocromatico.setGeometry(QtCore.QRect(350, 30, 411, 391))
        self.Label_Fonodo_Monocromatico.setStyleSheet("background-color: rgb(98, 7, 255);\n"
"border-radius : 20px")
        self.Label_Fonodo_Monocromatico.setText("")
        self.Label_Fonodo_Monocromatico.setObjectName("Label_Fonodo_Monocromatico")
        self.Label_Nombre = QtWidgets.QLabel(self.centralwidget)
        self.Label_Nombre.setGeometry(QtCore.QRect(500, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Label_Nombre.setFont(font)
        self.Label_Nombre.setStyleSheet("color: rgb(255, 255, 255);")
        self.Label_Nombre.setObjectName("Label_Nombre")
        self.Line_Apellido = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Apellido.setGeometry(QtCore.QRect(380, 120, 341, 20))
        self.Line_Apellido.setObjectName("Line_Apellido")
        self.Label_Contrasena = QtWidgets.QLabel(self.centralwidget)
        self.Label_Contrasena.setGeometry(QtCore.QRect(490, 150, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Label_Contrasena.setFont(font)
        self.Label_Contrasena.setStyleSheet("color: rgb(255, 255, 255);")
        self.Label_Contrasena.setObjectName("Label_Contrasena")
        self.Line_Contrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Contrasena.setGeometry(QtCore.QRect(380, 170, 341, 20))
        self.Line_Contrasena.setObjectName("Line_Contrasena")
        self.Label_Email = QtWidgets.QLabel(self.centralwidget)
        self.Label_Email.setGeometry(QtCore.QRect(520, 200, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Label_Email.setFont(font)
        self.Label_Email.setStyleSheet("color: rgb(255, 255, 255);")
        self.Label_Email.setObjectName("Label_Email")
        self.Line_Email = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Email.setGeometry(QtCore.QRect(380, 220, 341, 20))
        self.Line_Email.setStyleSheet("")
        self.Line_Email.setObjectName("Line_Email")
        self.Label_Fecha = QtWidgets.QLabel(self.centralwidget)
        self.Label_Fecha.setGeometry(QtCore.QRect(460, 260, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Label_Fecha.setFont(font)
        self.Label_Fecha.setStyleSheet("color: rgb(255, 255, 255);")
        self.Label_Fecha.setObjectName("Label_Fecha")
        self.Line_Nombre = QtWidgets.QLineEdit(self.centralwidget)
        self.Line_Nombre.setGeometry(QtCore.QRect(380, 70, 351, 20))
        self.Line_Nombre.setObjectName("Line_Nombre")
        self.Label_Apellido = QtWidgets.QLabel(self.centralwidget)
        self.Label_Apellido.setGeometry(QtCore.QRect(500, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Label_Apellido.setFont(font)
        self.Label_Apellido.setStyleSheet("color: rgb(255, 255, 255);")
        self.Label_Apellido.setObjectName("Label_Apellido")
        self.Fecha = QtWidgets.QDateEdit(self.centralwidget)
        self.Fecha.setGeometry(QtCore.QRect(380, 280, 341, 22))
        self.Fecha.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.Fecha.setObjectName("Fecha")
        self.Boton_Registro = QtWidgets.QPushButton(self.centralwidget)
        self.Boton_Registro.setGeometry(QtCore.QRect(480, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Boton_Registro.setFont(font)
        self.Boton_Registro.setObjectName("Boton_Registro")
        Window_Registro.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window_Registro)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 21))
        self.menubar.setObjectName("menubar")
        Window_Registro.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window_Registro)
        self.statusbar.setObjectName("statusbar")
        Window_Registro.setStatusBar(self.statusbar)

        self.retranslateUi(Window_Registro)
        QtCore.QMetaObject.connectSlotsByName(Window_Registro)

    def retranslateUi(self, Window_Registro):
        _translate = QtCore.QCoreApplication.translate
        Window_Registro.setWindowTitle(_translate("Window_Registro", "MainWindow"))
        self.Label_Nombre.setText(_translate("Window_Registro", "Nombre"))
        self.Label_Contrasena.setText(_translate("Window_Registro", "Contraseña"))
        self.Label_Email.setText(_translate("Window_Registro", "Email"))
        self.Label_Fecha.setText(_translate("Window_Registro", "Fecha de nacimiento"))
        self.Label_Apellido.setText(_translate("Window_Registro", "Apellido"))
        self.Boton_Registro.setText(_translate("Window_Registro", "Registrarse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window_Registro = QtWidgets.QMainWindow()
    ui = Ui_Window_Registro()
    ui.setupUi(Window_Registro)
    Window_Registro.show()
    sys.exit(app.exec_())
